name: me_voy_chofer
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dio: ^4.0.6
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  geolocator: ^8.0.1
  flutter_native_splash: ^2.1.1
  provider: ^6.0.3
  connectivity_plus: ^2.3.5
  internet_connection_checker: ^0.0.1+4
  flutter_map: ^1.1.1
  latlong2: ^0.8.0
  cached_network_image: ^3.2.0
  flutter_polyline_points: ^1.0.0
  flutter_secure_storage: ^5.0.2
  fluttertoast: ^8.0.8
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets: 
    - assets/
    - assets/images/
  uses-material-design: true
flutter_native_splash:
 color: "#FFFFFF"
 image: "assets/images/bus.png"
 android_12: